-- ============================================================================
-- Lenzora.lk — RESTORE SALES HISTORY FROM STATIC BACKUP
-- ============================================================================
-- Purpose: Re-insert sales-history records (sales, orders, frames,
--          payment_slips, invoices, invoice_items) that were backed up as
--          static INSERT statements, back into your Supabase database.
--
-- HOW TO USE:
--   1) Open your saved backup file (e.g. `sales-history-backup-<date>.sql`)
--      that you generated by running `backup-sales-history.sql`.
--   2) Copy ALL of the INSERT ... ON CONFLICT (id) DO NOTHING; blocks.
--   3) Paste them into this file BELOW the "PASTE YOUR BACKUP HERE" marker.
--   4) Supabase Dashboard -> SQL Editor -> New query -> paste -> RUN.
--
-- Order matters! Paste the tables in this order so foreign keys resolve:
--     1. sales         (no dependencies)
--     2. frames        (no dependencies)
--     3. payment_slips (needs orders - see 4)
--     4. orders        (references payment_slips, products, services)
--     5. invoices      (references orders)
--     6. invoice_items (references invoices)
--
-- NOTE: payment_slips references orders, and orders references payment_slips
--       (payment_slip_id). If both reference each other, temporarily disable
--       the FK checks (see below) before inserting, then re-enable.
-- ============================================================================

BEGIN;

-- Optionally disable FK checks during restore (re-enabled below).
SET session_replication_role = replica;

-- ============================================================================
-- >>>>>  PASTE YOUR BACKUP INSERT STATEMENTS HERE  <<<<<
-- (One block per table, in the order shown above.)
-- Example:
--   INSERT INTO public.sales (id, item_name, amount, notes, created_at)
--   VALUES ('1', 'Logo', '15000', 'Client order', '2026-01-15 10:00:00+00')
--   ON CONFLICT (id) DO NOTHING;
-- ============================================================================

-- Re-enable FK checks.
SET session_replication_role = DEFAULT;

COMMIT;

-- ---------------------------------------------------------------------------
-- Verify: this should now show your past rows again.
-- ---------------------------------------------------------------------------
SELECT 'sales' AS table_name, count(*), COALESCE(sum(amount),0) AS total FROM public.sales
UNION ALL SELECT 'orders', count(*), COALESCE(sum(amount),0) FROM public.orders
UNION ALL SELECT 'frames', count(*), COALESCE(sum(profit),0) FROM public.frames
UNION ALL SELECT 'payment_slips', count(*), 0 FROM public.payment_slips
UNION ALL SELECT 'invoices', count(*), COALESCE(sum(total),0) FROM public.invoices
UNION ALL SELECT 'invoice_items', count(*), 0 FROM public.invoice_items
ORDER BY table_name;
